name: 'GRM SoonerECHO chapter '
favicon: null
layout_spectrum: 0.9398975425865501
typography_spectrum: 0.9904813785105944
title: Oklahoma Chapter of the GRM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#669966'
    - '#040300'
    - '#eba100'
    - '#c900f6'
  brandStrength: 0.8125
  lightness: 0.0843763523735106
  saturation: 0.6940320425201207
  rhythmicContrast: 0.047630531480535865
purpose: []
