name: 'GRM SoonerECHO chapter '
favicon: null
layout_spectrum: 0.74854
typography_spectrum: 0.80928
title: Oklahoma Chapter of the GRM
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#669966'
    - '#040300'
    - '#eba100'
    - '#c900f6'
  brandStrength: 0.8125
  lightness: 0.125
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
